import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import {Metadata} from "next"

const inter = Inter({ subsets: ["latin"] });

export const viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: false,
};

export const metadata =  {
  title: "Cedar Valley Roofing",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
};
